  - name: Include vars
    include_vars: cassandra_config.yml

  - name: Stop cassandra systemd service
    systemd:
      name: cassandra-{{ CASSANDRA_VERSION }}.service
      state: stopped

  - name: Edit cluster configuration
    lineinfile:
      dest: /opt/cassandra/apache-cassandra-{{ CASSANDRA_VERSION }}/conf/cassandra.yaml
      regexp: '- seeds: '
      line: '      - seeds: "{{ CLUSTER_HOSTS_LIST }}"'
      backup: yes
      state: present

  - name: Copy cassandra rackdc properties config
    template:
      src: cassandra-rackdc.properties.j2
      dest: /opt/cassandra/apache-cassandra-{{ CASSANDRA_VERSION }}/conf/cassandra-rackdc.properties
      owner: cassandra
      group: cassandra
      mode: 0755

  - name: Restart cassandra systemd service
    systemd:
      name: cassandra-{{ CASSANDRA_VERSION }}.service
      state: restarted


